server:
    port: 8761

spring:
  application:
    name: eureka-service
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: http://host.docker.internal:9411

    
eureka: 
    client:
        register-with-eureka: false
        fetch-registry: false


logging:
  level:
    org:
     springframework:
      web:
       servlet:
        DispatcherServlet: TRACE